spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google
            client-secret: secret
            scope:
              - email
              - profile


          naver:
            client-id: naverid
            client-secret: naversecret
            redirect-uri: http://springboot-developer-env.eba-gusjzjzw.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email


          kakao:
            client-id: kakaoid
            client-secret: kakaosecret
            redirect-uri: http://springboot-developer-env.eba-gusjzjzw.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id






file:
  profileImagePath: C:\Temp\profileImageUpload\

jwt:
  issuer: ajufresh@gmail.com
  secret_key: test_key
