INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('기술', '내용', 'dlalstn7894@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('기능', '내용', 'dlalstn7894@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('MyDiary가 오픈되었습니다!', '내용', 'user1', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('첫번째 글을 써볼까???', '내용', 'user2', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('두번째 글도 잘 작성되요', '내용', 'user3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('홈페이지에선 최신 10개의 글만보이게 랜더링 했습니다', '내용', 'user3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('jwt 토큰기반 인증을 사용합니다', '내용', 'user3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('그리고 oauth2를 사용해서 kakao google naver 계정으로 인증이 가능합니다', '내용', 'user3', NOW(), NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES (3,'user1','댓글 기능도 오픈되었습니다!',NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES (3,'user2','첫번째 댓글을 써볼까???!',NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES (4,'user1','comments와 article은 다대일 관계입니다',NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES (4,'user2','articleImage와 article또한 다대일 관계입니다',NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES (5,'user1','홈페이지에서도 잘보여요',NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('spring은 엔터프라이즈 어플리케이션을 쉽게 개발할수 있도록 도와주는 프레임워크입니다', '내용', 'spring', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('spring boot는 스프링을 더 빠르고 쉽게 사용할수있도록 스타터와 자동구성을 제공해주는 도구입니다', '내용', 'spring', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('spring의 중요한 특성인 DI는 객체 간의 의존성을 외부에서 주입받아 애플리케이션의 유연성과 테스트 용이성을 높여줍니다', '내용', 'spring', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('springSecurity는 스프링기반 어플리케이션의 보안을 담당합니다  ', '내용', 'spring', NOW(), NOW())
